//
//  GeneratedPluginRegistrant.swift
//  Runner
//
//  Generated by the Flutter build system to register plugins.
//  This file is generated by Flutter. Do not edit by hand.
//

import FlutterMacOS

func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
  // Plugins são registrados automaticamente pelo Flutter
}

import UIKit
import Firebase
import FirebaseMessaging

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, MessagingDelegate {
  
  func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    
    // ========== FIREBASE SETUP ==========
    // Configurar Firebase com GoogleService-Info.plist
    FirebaseApp.configure()
    
    // ========== PUSH NOTIFICATIONS ==========
    // Delegate para push notifications
    UNUserNotificationCenter.current().delegate = self
    Messaging.messaging().delegate = self
    
    // Request permissão de notificações (iOS 10+)
    UNUserNotificationCenter.current().requestAuthorization(
      options: [.alert, .sound, .badge]
    ) { granted, error in
      if granted {
        DispatchQueue.main.async {
          UIApplication.shared.registerForRemoteNotifications()
        }
      }
    }
    
    // ========== LOGGING DIAGNOSTICS ==========
    #if DEBUG
    let token = Messaging.messaging().fcmToken
    print("✅ Firebase inicializado")
    print("🔔 FCM Token: \(token ?? "não disponível ainda")")
    #endif
    
    return true
  }
  
  // ========== REMOTE NOTIFICATION HANDLERS ==========
  
  /// Chamado quando recebe remote notification em background
  func application(
    _ application: UIApplication,
    didReceiveRemoteNotification userInfo: [AnyHashable: Any],
    fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void
  ) {
    // Firebase automatically handles message routing
    completionHandler(.newData)
  }
  
  /// Chamado quando app registra para remote notifications
  func application(
    _ application: UIApplication,
    didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data
  ) {
    // APNs token para Firebase
    Messaging.messaging().apnsToken = deviceToken
    #if DEBUG
    print("✅ APNs Token registrado")
    #endif
  }
  
  /// Chamado quando falha ao registrar para remote notifications
  func application(
    _ application: UIApplication,
    didFailToRegisterForRemoteNotificationsWithError error: Error
  ) {
    print("❌ Erro ao registrar para notificações remotas: \(error.localizedDescription)")
  }
  
  // ========== FIREBASE MESSAGING DELEGATES ==========
  
  /// Chamado quando novo FCM token é gerado
  func messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String) {
    #if DEBUG
    print("🔄 Novo FCM Token: \(fcmToken)")
    #endif
    
    // Notificar Flutter do novo token
    DispatchQueue.main.async {
      // O SDK do Firebase no Flutter já ouve esse evento automaticamente
      // Mas você pode fazer algo adicional aqui se necessário
      NotificationCenter.default.post(
        name: NSNotification.Name("FCMTokenRefreshed"),
        object: fcmToken
      )
    }
  }
}

// ========== NOTIFICATION DELEGATE ==========
extension AppDelegate: UNUserNotificationCenterDelegate {
  
  /// Chamado quando notificação chega em foreground
  func userNotificationCenter(
    _ center: UNUserNotificationCenter,
    willPresent notification: UNNotification
  ) async -> UNNotificationPresentationOptions {
    
    let userInfo = notification.request.content.userInfo
    
    // Deixar o Flutter/Firebase Messaging lidar
    // mas também log aqui se necessário
    #if DEBUG
    print("📬 Notificação em foreground: \(userInfo)")
    #endif
    
    return [[.banner, .sound, .badge]]
  }
  
  /// Chamado quando usuário toca em notificação
  func userNotificationCenter(
    _ center: UNUserNotificationCenter,
    didReceive response: UNNotificationResponse
  ) async {
    
    let userInfo = response.notification.request.content.userInfo
    
    // Firebase Messaging + Flutter já tratam isso
    // Mas você pode fazer algo adicional aqui
    #if DEBUG
    print("👆 Notificação tocada: \(userInfo)")
    #endif
  }
}
